name: Rector
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
      - name: Composer
        run: composer install --no-progress --no-suggest --no-interaction
      - name: Rector dry-run
        run: ./vendor/bin/rector process --dry-run
        
